name: Tests_and_Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  run_unit_tests:          
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}  
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: swe4s
      - run: |
          cd test/unit
          python -m unittest test_my_utils

  run_func_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}  
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: swe4s
      - run:
          bash test/func/test_print_fires.sh
         
  run_style_checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}  
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: swe4s
      - run:
          pycodestyle $(git ls-files "*.py")  
  
  
         