name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -run:
         cd test/unit
         python -m unittest test_my_utils

  run_func_tests:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -run:
         bash test/func/test_print_fires.sh
         
  run_style_checks:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -run:
         pycodestyle $(git ls-files "*.py")
         